# map kitty_mod ctrl+shift
action_alias launch_tab launch --cwd=current --type=tab


# ░█▀▀░█▀█░█▀█░▀█▀░█▀▀
# ░█▀▀░█░█░█░█░░█░░▀▀█
# ░▀░░░▀▀▀░▀░▀░░▀░░▀▀▀
map ctrl+shift+equal    	increase_font_size
map ctrl+shift+minus    	decrease_font_size
map ctrl+shift+backspace 	restore_font_size

# ░█▀▀░█░░░▀█▀░█▀█░█▀▄░█▀█░█▀█░█▀▄░█▀▄
# ░█░░░█░░░░█░░█▀▀░█▀▄░█░█░█▀█░█▀▄░█░█
# ░▀▀▀░▀▀▀░▀▀▀░▀░░░▀▀░░▀▀▀░▀░▀░▀░▀░▀▀░
map ctrl+shift+c copy_to_clipboard

map ctrl+shift+v paste_from_clipboard
map ctrl+shift+s paste_from_selection
map shift+insert paste_from_selection

map ctrl+shift+o pass_selection_to_program firefox
# map kitty_mod+y new_window less @selection


# ░█▀▀░█▀▀░█▀▄░█▀█░█░░░█░░░▀█▀░█▀█░█▀▀
# ░▀▀█░█░░░█▀▄░█░█░█░░░█░░░░█░░█░█░█░█
# ░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀
map ctrl+shift+k scroll_line_up
map ctrl+shift+j scroll_line_down
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down

map ctrl+shift+page_up scroll_page_up
map ctrl+shift+page_down scroll_page_down

map ctrl+shift+home scroll_home
map ctrl+shift+end scroll_end

map ctrl+shift+h show_scrollback


# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▄█░█▀█░█▀█░█▀█░█▀▀░█▀▀░█▄█░█▀▀░█▀█░▀█▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█░█░█▀█░█░█░█▀█░█░█░█▀▀░█░█░█▀▀░█░█░░█░
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░░▀░
map ctrl+shift+n new_os_window
map ctrl+shift+enter launch --cwd=current

map ctrl+shift+y launch ncdu

map ctrl+shift+n new_os_window
map ctrl+shift+w close_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
# map ctrl+shift+f move_window_forward
# map ctrl+shift+b move_window_backward
map ctrl+shift+r start_resizing_window
# map ctrl+shift+f7 focus_visible_window

# Move the active window in the indicated direction
map shift+up                                move_window up
map shift+left                              move_window left
map shift+right                             move_window right
map shift+down                              move_window down

# ░▀█▀░█▀█░█▀▄░░░█▄█░█▀█░█▀█░█▀█░█▀▀░█▀▀░█▄█░█▀▀░█▀█░▀█▀
# ░░█░░█▀█░█▀▄░░░█░█░█▀█░█░█░█▀█░█░█░█▀▀░█░█░█▀▀░█░█░░█░
# ░░▀░░▀░▀░▀▀░░░░▀░▀░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░░▀░
map ctrl+shift+t        					new_tab
map ctrl+shift+q        					close_tab
map ctrl+shift+right    					next_tab
map ctrl+shift+left     					previous_tab
map ctrl+shift+.        					move_tab_forward
map ctrl+shift+,        					move_tab_backward
map ctrl+shift+alt+t    					set_tab_title

# map ctrl+shift+1        					goto_tab_1
# map ctrl+shift+2        					goto_tab_2
# map ctrl+shift+3        					goto_tab_3
# map ctrl+shift+4        					goto_tab_4

map ctrl+t new_tab !neighbor htop


# ░█░░░█▀█░█░█░█▀█░█░█░▀█▀░░░█▄█░█▀█░█▀█░█▀█░█▀▀░█▀▀░█▄█░█▀▀░█▀█░▀█▀
# ░█░░░█▀█░░█░░█░█░█░█░░█░░░░█░█░█▀█░█░█░█▀█░█░█░█▀▀░█░█░█▀▀░█░█░░█░
# ░▀▀▀░▀░▀░░▀░░▀▀▀░▀▀▀░░▀░░░░▀░▀░▀░▀░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░░▀░
map F4  close_window

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side if the existing window is wide or
# one above the other if the existing window is tall.
map F5  launch --location=split --cwd=current

# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map F6  launch --location=hsplit --cwd=current

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side
map F7  launch --location=vsplit --cwd=current

# Rotate the current split, chaging its split axis from vertical to
# horizontal or vice versa
map F8  layout_action rotate

map ctrl+shift+F9                           kitty @ detach-tab --self
