# ░█░█░▀█▀░▀█▀░▀█▀░█░█
# ░█▀▄░░█░░░█░░░█░░░█░
# ░▀░▀░▀▀▀░░▀░░░▀░░░▀░
include scheme/everblush.conf
include keybindings.conf

# ░█▀▀░█▀█░█▀█░▀█▀░█▀▀
# ░█▀▀░█░█░█░█░░█░░▀▀█
# ░▀░░░▀▀▀░▀░▀░░▀░░▀▀▀
# font_family         JetBrains Mono Nerd Font
font_family         Terminus (TTF)
font_size           15

disable_ligatures   never

adjust_line_height  2
adjust_column_width 0


# ░█▀▀░█░█░█▀▄░█▀▀░█▀█░█▀▄
# ░█░░░█░█░█▀▄░▀▀█░█░█░█▀▄
# ░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀░▀
cursor_shape				underline
cursor_beam_thickness		2
cursor_underline_thickness	2.5

# ░█▀▀░█▀▀░█▀▄░█▀█░█░░░█░░░█▀▄░█▀█░█▀▀░█░█
# ░▀▀█░█░░░█▀▄░█░█░█░░░█░░░█▀▄░█▀█░█░░░█▀▄
# ░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀░░▀░▀░▀▀▀░▀░▀
scrollback_lines 		-1
scrollback_pager 		usr/bin/less


# ░█▄█░█▀█░█░█░█▀▀░█▀▀
# ░█░█░█░█░█░█░▀▀█░█▀▀
# ░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀
focus_follows_mouse	no

detect_urls		yes
url_color		#ff0000
url_style		curly
open_url_with 	default

underline_hyperlinks	hover
show_hyperlink_targets	yes

copy_on_select 				yes
select_by_word_characters 	:@-./_~?&=%+#


# ░█▀▄░█▀▀░█░░░█░░
# ░█▀▄░█▀▀░█░░░█░░
# ░▀▀░░▀▀▀░▀▀▀░▀▀▀
enable_audio_bell 		no

# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█
# ░█▄█░░█░░█░█░█░█░█░█░█▄█
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀
initial_window_width	900
initial_window_height	576
remember_window_size	no

confirm_os_window_close 0

window_border_width 	1
# window_margin_width 	0
draw_minimal_borders	yes
window_padding_width 	10

background_opacity 	.8
hide_window_decorations no


# ░▀█▀░█▀█░█▀▄░█▀▀
# ░░█░░█▀█░█▀▄░▀▀█
# ░░▀░░▀░▀░▀▀░░▀▀▀
tab_bar_edge 			bottom
tab_bar_margin_width 	0.0
# tab_bar_margin_height 	0.0

tab_bar_style 	slant
tab_bar_align	left
tab_separator 	" ┇ "

tab_activity_symbol "*"
tab_title_template	"{fmt.fg.green}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.active_exe}"

# ░█▀▀░█░█░█▀▀░█░░░█░░
# ░▀▀█░█▀█░█▀▀░█░░░█░░
# ░▀▀▀░▀░▀░▀▀▀░▀▀▀░▀▀▀
shell 			.
shell_integration   no-cursor

close_on_child_death no
allow_remote_control yes

term 				xterm-256color
allow_hyperlinks	yes

