foreground #dadada
background #141b1e   
cursor  #bdc3c2
color0  #181f21
color1  #e06e6e
color2  #8ccf7e
color3  #e5c76b
color4  #67b0e8
color5  #c47fd5
color6  #6da4cd
color7  #b3b9b8
color8  #181f21
color9  #ef7d7d
color10 #9bdead
color11 #f4d67a
color12 #6cb5ed
color13 #ce89df
color14 #67cbe7
color15 #bdc3c2 
selection_foreground #dadada
selection_background #3b4244

# Tabs 

tab_bar_edge bottom 
tab_bar_style powerline 

tab_separator "|"

active_tab_foreground #9bdead
active_tab_background #ffffff
inactive_tab_foreground #bac0bf
inactive_tab_background #232a2c
active_tab_font_style 						bold
inactive_tab_font_style 					normal

active_border_color #9bdead
inactive_border_color #6a6a6a
