foreground   #b1d7c6
background   #0B1116
cursor       #b1d7c6

color0       #0B1116
color8       #7b968a
color1       #585C60
color9       #585C60
color2       #A1684F
color10      #A1684F
color3       #BF9269
color11      #BF9269
color4       #607889
color12      #607889
color5       #8A7D80
color13      #8A7D80
color6       #718E9C
color14      #718E9C
color7       #b1d7c6
color15      #b1d7c6

selection_foreground #dadada
selection_background #BF9269

# Tabs 

tab_bar_edge bottom 
tab_bar_style powerline 

tab_separator "|"

active_tab_foreground #9bdead
active_tab_background #ffffff
inactive_tab_foreground #bac0bf
inactive_tab_background #232a2c
active_tab_font_style 						bold
inactive_tab_font_style 					normal

active_border_color #9bdead
inactive_border_color #6a6a6a
