foreground   #8ecace
background   #120e10
cursor       #8ecace

color0       #120e10
color8       #638d90
color1       #1B8E73
color9       #1B8E73
color2       #E0A549
color10      #E0A549
color3       #F7DA5C
color11      #F7DA5C
color4       #076A8A
color12      #076A8A
color5       #4D768B
color13      #4D768B
color6       #D37087
color14      #D37087
color7       #8ecace
color15      #8ecace
